on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: 5monkeys/cobertura-action@master
        with:
          path: reports/cobertura-coverage.xml
          minimum_coverage: 75
